openapi: 3.0.4
info:
  version: '1.0'
  title: "AiLERT API"
  description: API for the AiLERT application.
  license:
    name: MIT

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://example.com/api/v1
    description: Production server

paths:
  /auth/login:
    post:
      summary: User Login
      description: 
        Authenticate user and generate JWT token. **IMPORTANT:** Ensure to use HTTPS in production for security.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            examples:
              example1:
                value:
                  email: 'john.doe@example.com'
                  password: 'securepassword123'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/changepass:
    post:
      summary: Change Password
      description: 
        Change the user's password. Requires authentication.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newpassword:
                  type: string
                  description: New password
                
            examples:
              example1:
                value:
                  newpassword: 'newSecurePassword456'
                summary: Standard password change request
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the password change was successful
                  message:
                    type: string
                    description: Success message
              examples:
                success:
                  value:
                    success: true
                    message: 'Password changed successfully'
        '401':
          description: Unauthorized access (invalid user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                userNotFound:
                  value:
                    error: 'Invalid email'
                    errorCode: 'INVALID_EMAIL'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidToken:
                  value:
                    error: 'Invalid or expired token'
                    errorCode: 'INVALID_TOKEN'
  /events:
    get:
      summary: Ottieni tutti gli eventi
      description: Restituisce la lista di eventi. Richiede autenticazione.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lista ottenuta con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '401':
          description: Utente non autenticato
    post:
      summary: Crea un nuovo evento
      description: Registra un nuovo evento (incidente o ingorgo). Richiede autenticazione.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Evento creato con successo
        '400':
          description: Errore nei dati inviati
        '401':
          description: Utente non autenticato


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: User's email address
        password:
          type: string
          description: User's password
          format: password

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT access token
        success:
          type: boolean
          description: Whether the login was successful

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        errorCode:
          type: string
          description: Specific error code for the failure
    
    Event:
      type: object
      properties:
        type:
          type: string
          enum: [incidente, ingorgo]
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        eventDate:
          type: string
          format: date-time
        location:
          type: object
          properties:
            address:
              type: string
        status:
          type: string
          enum: [pending, solved, unsolved, false_alarm]
        cameraId:
          type: string
        videoUrl:
          type: string
        confirmed:
          type: boolean
        confirmedBy:
          type: string
        notifiedServices:
          type: array
          items:
            type: object
            properties:
              service:
                type: string
                enum: [polizia, carabinieri, vigili_del_fuoco, ambulanza, protezione_civile]
              notifiedAt:
                type: string
                format: date-time
              responseTime:
                type: number
        severity:
          type: string
          enum: [bassa, media, alta]
